# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageGallery' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.7'
  pod 'FontAwesome.swift', '~> 1.4.8'
  pod 'MBProgressHUD', '~> 1.1.0'
end
